kind: Pod
apiVersion: v1
metadata:
  name: iscsi-provisioner
spec:
  containers:
    - name: iscsi-provisioner
      image: hchiramm/iscsi-provisioner
      args:
        - "-provisioner-name=iscsi-provisioner"
      imagePullPolicy: "IfNotPresent"
